#!/bin/bash

docker run -v /home/travis/build/Multiscale-Genomics/mg-process-fastq/tests/data:/RehamCode/bin multiscalegenomics/mgprocessfastq:biobambamimage /RehamCode/lib/biobambam2/bin/bamsormadup $@ 
