#!/bin/bash

exec docker run  multiscalegenomics/mgprocessfastq:biobambamimage -v /home/travis/build/Multiscale-Genomics/mg-process-fastq/tests/data:/RehamCode/bin /RehamCode/lib/biobambam2/bin/bamsormadup $@ 
