language: "python"

python:
  - "2.7.12"
#  - "3.5.0"

#sudo: false

addons:
  apt:
    packages:
    #system environment
    - make 
    - python-dev
    - build-essential
    - libssl-dev 
    - zlib1g-dev
    - libbz2-dev 
    - libreadline-dev
    - libsqlite3-dev 
    - libtiff5-dev
    - libjpeg8-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev 
    - tk8.6-dev 
    - python-tk
    - wget 
    - curl 
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - mcl 
    - libgtk2.0-dev 
    - r-base-core
    - python-rpy2
    - libcurl4-gnutls-dev
    - unzip   
    - samtools

env:
  - COVERALLS=false
  
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
    - pwd
    - mkdir -p ${HOME}/bin 
    - mkdir -p ${HOME}/lib
    - pip --version
    - which R
    - pip
    - lsb_release -a
    - pwd


services:
    - docker
    
install:

    - pwd  
    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq
    #- cd 
    
before_script : 
    - cd ${HOME}/bin
    - docker run -p 80:80 --name biobambamcontainer -v /Users/reham/bin:/RehamCode/bin  multiscalegenomics/mgprocessfastq:biobambamimage
    - docker start -i biobambamcontainer
    - cd /RehamCode/bin
    - ln -s ${HOME}/lib/biobambam2/bin/bamcat bamcat
    - ln -s ${HOME}/lib/biobambam2/bin/bamexplode bamexplode
    - ln -s ${HOME}/lib/biobambam2/bin/bam12split bam12split
    - docker stop biobambamcontainer
    - bam12split
    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq


script : 
     pytest ./tests/test_bwa_indexer.py

