language: "python"

python:
  - "2.7.12"
#  - "3.5.0"

#sudo: false

addons:
  apt:
    packages:
    #system environment
    - make 
    - python-dev
    - build-essential
    - libssl-dev 
    - zlib1g-dev
    - libbz2-dev 
    - libreadline-dev
    - libsqlite3-dev 
    - libtiff5-dev
    - libjpeg8-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev 
    - tk8.6-dev 
    - python-tk
    - wget 
    - curl 
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - mcl 
    - libgtk2.0-dev 
    - r-base-core
    - python-rpy2
    - libcurl4-gnutls-dev
    - unzip   
    - samtools

env:
  - COVERALLS=false
  
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
    - pwd
    - mkdir -p ${HOME}/bin 
    - mkdir -p ${HOME}/lib
    - pip --version
    - which R
    - pip
    - lsb_release -a
    - pwd


services:
    - docker
    
install:

    - pwd  
    #UCSC Tools
    - cd ${HOME}/lib
    - wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed
    - wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig
    
    
    
    #Bowtie2 Aligner
    - cd ${HOME}/lib
    - wget --max-redirect 1 https://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.3.2/bowtie2-2.3.2-linux-x86_64.zip
    - unzip bowtie2-2.3.2-linux-x86_64.zip


    #BWA Sequence Aligner
    - cd ${HOME}/lib
    - git clone https://github.com/lh3/bwa.git
    - cd bwa
    - make

    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq    
    - ls
    
before_script : 
    - cd ${HOME}  
    - pwd
    - ls /home/travis/build/Multiscale-Genomics/mg-process-fastq
    - bam12split
    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq


script : 
     pytest ./tests/test_bwa_indexer.py

