language: "python"

python:
  - "2.7.12"
#  - "3.5.0"

sudo: false

addons:
  apt:
    packages:
    #system environment
    - make 
    - build-essential
    - libssl-dev 
    - zlib1g-dev
    - libbz2-dev 
    - libreadline-dev
    - libsqlite3-dev 
    - wget curl 
    - llvm libncurses5-dev
    - libncursesw5-dev
    - xz-utils tk-dev
    - unzip mcl 
    - libgtk2.0-dev 
    - r-base-core
    - libcurl4-gnutls-dev
    - unzip   

env:
  - COVERALLS=false

before_install:

    #pyenv-pyenv-virtualenv
    - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
    - echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
    - echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
    
#install:

#script : "./tests/test_biobambam.py"

