language: "python"

python:
  - "2.7.12"
#  - "3.5.0"

#sudo: false

addons:
  apt:
    packages:
    #system environment
    - make 
    - build-essential
    - libssl-dev 
    - zlib1g-dev
    - libbz2-dev 
    - libreadline-dev
    - libsqlite3-dev 
    - wget curl 
    - llvm libncurses5-dev
    - libncursesw5-dev
    - xz-utils tk-dev
    - unzip mcl 
    - libgtk2.0-dev 
    - r-base-core
    - libcurl4-gnutls-dev
    - unzip   

env:
  - COVERALLS=false
  
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
    - cd ${HOME}
    - mkdir bin lib code
    - pip --version
    - which R
    - pip
    - lsb_release -a

    
install:

     #SAMtools
    - cd ${HOME}/lib
    - git clone https://github.com/samtools/htslib.git
    - cd htslib
    - autoheader
    - autoconf
    - ./configure --prefix=${HOME}/lib/htslib
    - make
    - make install

    - cd ${HOME}/lib
    - sudo apt-get install samtools   
    
    ##Prepare the Python Environment
     #Install APIs and Pipelines
    - cd ${HOME}/code
    #- pyenv #activate mg-process-fastq
    - pip install git+https://github.com/Multiscale-Genomics/mg-dm-api.git

    - git clone https://github.com/Multiscale-Genomics/mg-process-fastq.git
    - cd mg-process-fastq
    - sudo apt-get install python-dev
    - pip install --upgrade pip
    - pip install -U setuptools
    - pip install .

    

#script : "./tests/test_biobambam.py"

