language: "python"

python:
  - "2.7.12"
#  - "3.5.0"

#sudo: false

addons:
  apt:
    packages:
    #system environment
    - make 
    - python-dev
    - build-essential
    - libssl-dev 
    - zlib1g-dev
    - libbz2-dev 
    - libreadline-dev
    - libsqlite3-dev 
    - libtiff5-dev
    - libjpeg8-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev 
    - tk8.6-dev 
    - python-tk
    - wget 
    - curl 
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - mcl 
    - libgtk2.0-dev 
    - r-base-core
    - python-rpy2
    - libcurl4-gnutls-dev
    - unzip   
    - samtools

env:
  - COVERALLS=false
  
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
    - pwd
    - mkdir ${HOME}/bin 
    - mkdir ${HOME}/lib
    - pip --version
    - which R
    - pip
    - lsb_release -a
    - pwd

    
install:

    - pwd
    - pip install git+https://github.com/Multiscale-Genomics/mg-dm-api.git
    - pip install --editable .
    - pip install pytest
    
     #SAMtools
    - cd ${HOME}/lib
    - git clone https://github.com/samtools/htslib.git
    - cd htslib
    - autoheader
    - autoconf
    - ./configure --prefix=${HOME}/lib/htslib
    - make
    - make install
    
    ##Prepare the Python Environment

    #- pip install --upgrade pip  
    #- pip install setuptools
    - echo ${HOME}
    #- cd 

script : 
     pytest ./tests/test_bwa_indexer.py

