# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: "python"

python:
  - "2.7.12"
  - "3.5.2"

#sudo: false

addons:
  apt:
    packages:
    #system environment
    - make
    - python-dev
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - libtiff5-dev
    - libjpeg8-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev
    - tk8.6-dev
    - python-tk
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - mcl
    - libgtk2.0-dev
    - r-base-core
    - python-rpy2
    - libcurl4-gnutls-dev
    - unzip
    - liblzma-dev
    - libtool
    - pigz
    #- libtbb2

#env:
#  - COVERALLS=false

before_install:
    - pwd
    - ls /usr/lib/
    - mkdir -p ${HOME}/bin
    - mkdir -p ${HOME}/lib
    - mkdir -p ${HOME}/code
    - lsb_release -a

services:
    - docker

install:
    # libtbb-dev did not seem to be installing correctly without using sudo
    - sudo apt-get install libtbb-dev

    # Install APIs and Pipelines
    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq
    - git status
    - pip install -e .
    - pip install -r requirements.txt

    # htslib
    - cd ${HOME}/lib
    - git clone https://github.com/samtools/htslib.git
    - cd htslib
    - autoheader
    - autoconf
    - ./configure --prefix=${HOME}/lib/htslib
    - make
    - make install

    # SAMtools
    - cd ${HOME}/lib
    - git clone https://github.com/samtools/samtools.git
    - cd samtools
    - autoheader
    - autoconf -Wno-syntax
    - ./configure --prefix=${HOME}/lib/samtools
    - make
    - make install

    # UCSC Tools
    - cd ${HOME}/lib
    - wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed
    - wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig

    # Bowtie2 Aligner
    - cd ${HOME}/lib
    - wget --max-redirect 1 https://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.3.2/bowtie2-2.3.2-linux-x86_64.zip
    - unzip bowtie2-2.3.2-linux-x86_64.zip

    # BWA Sequence Aligner
    - cd ${HOME}/lib
    - git clone https://github.com/lh3/bwa.git
    - cd bwa
    - make

    # GEM Indexer
    - cd ${HOME}/lib
    - wget http://barnaserver.com/gemtools/releases/GEMTools-static-core2-1.7.1.tar.gz
    - tar -xzf GEMTools-static-core2-1.7.1.tar.gz

    # iNPS Peak Caller
    #- cd ${HOME}/lib
    #- mkdir iNPS
    #- cd iNPS
    #- wget http://www.picb.ac.cn/hanlab/files/iNPS_V1.2.2.zip
    #- unzip iNPS_V1.2.2.zip

    # Kallisto
    - cd ${HOME}/lib
    - wget https://github.com/pachterlab/kallisto/releases/download/v0.43.1/kallisto_linux-v0.43.1.tar.gz
    - tar -xzf kallisto_linux-v0.43.1.tar.gz

    # bedTools
    - wget https://github.com/arq5x/bedtools2/releases/download/v2.26.0/bedtools-2.26.0.tar.gz
    - tar -zxvf bedtools-2.26.0.tar.gz
    - cd bedtools2
    - make
    # - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq

    # Install MACS2
    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq
    - chmod +x scripts/travis/includeMAC2.sh
    - ./scripts/travis/includeMAC2.sh

    # Install TADbit (only on Python 2.7)
    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq
    - chmod +x scripts/travis/includeTADbit.sh
    - ./scripts/travis/includeTADbit.sh

    # Install BSseeker
    - cd ${HOME}/lib
    - git clone https://github.com/BSSeeker/BSseeker2.git

    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq
    - ln -s ${HOME}/lib/BSseeker2/bs_align bs_align
    - ln -s ${HOME}/lib/BSseeker2/bs_index bs_index
    - ln -s ${HOME}/lib/BSseeker2/bs_utils bs_utils
    - ln -s ${HOME}/lib/BSseeker2/FilterReads.py FilterReads.py

    # Post Installation Tidyup
    - cd ${HOME}/lib
    - rm *.zip *.tar.gz

before_script :
    - cd ${HOME}/bin

    - ln -s ${HOME}/lib/bedtools2/bin/bedtools bedtools

    - ln -s ${HOME}/lib/bedToBigBed bedToBigBed
    - ln -s ${HOME}/lib/wigToBigWig wigToBigWig
    #- ln -s ${HOME}/lib/iNPS_V1.2.2.py iNPS_V1.2.2.py
    - ln -s ${HOME}/lib/kallisto_linux-v0.43.1/kallisto kallisto

    - ln -s ${HOME}/lib/bwa/bwa bwa

    - ln -s ${HOME}/lib/bowtie2-2.3.2/bowtie2 bowtie2
    - ln -s ${HOME}/lib/bowtie2-2.3.2/bowtie2-align-s bowtie2-align-s
    - ln -s ${HOME}/lib/bowtie2-2.3.2/bowtie2-align-l bowtie2-align-l
    - ln -s ${HOME}/lib/bowtie2-2.3.2/bowtie2-build bowtie2-build
    - ln -s ${HOME}/lib/bowtie2-2.3.2/bowtie2-build-s bowtie2-build-s
    - ln -s ${HOME}/lib/bowtie2-2.3.2/bowtie2-build-l bowtie2-build-l
    - ln -s ${HOME}/lib/bowtie2-2.3.2/bowtie2-inspect bowtie2-inspect
    - ln -s ${HOME}/lib/bowtie2-2.3.2/bowtie2-inspect-s bowtie2-inspect-s
    - ln -s ${HOME}/lib/bowtie2-2.3.2/bowtie2-inspect-l bowtie2-inspect-l

    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-2-bed gem-2-bed
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-2-gem gem-2-gem
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-2-sam gem-2-sam
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-2-wig gem-2-wig
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-indexer gem-indexer
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-indexer_bwt-dna gem-indexer_bwt-dna
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-indexer_fasta2meta+cont gem-indexer_fasta2meta+cont
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-indexer_generate gem-indexer_generate
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-info gem-info
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gem-mapper gem-mapper
    - ln -s ${HOME}/lib/gemtools-1.7.1-core2/bin/gemtools gemtools

    - ln -s ${HOME}/lib/htslib/bin/bgzip bgzip
    - ln -s ${HOME}/lib/htslib/bin/htsfile htsfile
    - ln -s ${HOME}/lib/htslib/bin/tabix tabix

    - ln -s ${HOME}/lib/samtools/bin/ace2sam ace2sam
    - ln -s ${HOME}/lib/samtools/bin/blast2sam.pl blast2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/bowtie2sam.pl bowtie2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/export2sam.pl export2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/interpolate_sam.pl interpolate_sam.pl
    - ln -s ${HOME}/lib/samtools/bin/maq2sam-long maq2sam-long
    - ln -s ${HOME}/lib/samtools/bin/maq2sam-short maq2sam-short
    - ln -s ${HOME}/lib/samtools/bin/md5fa md5fa
    - ln -s ${HOME}/lib/samtools/bin/md5sum-lite md5sum-lite
    - ln -s ${HOME}/lib/samtools/bin/novo2sam.pl novo2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/plot-bamstats plot-bamstats
    - ln -s ${HOME}/lib/samtools/bin/psl2sam.pl psl2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/sam2vcf.pl sam2vcf.pl
    - ln -s ${HOME}/lib/samtools/bin/samtools samtools
    - ln -s ${HOME}/lib/samtools/bin/samtools.pl samtools.pl
    - ln -s ${HOME}/lib/samtools/bin/seq_cache_populate.pl seq_cache_populate.pl
    - ln -s ${HOME}/lib/samtools/bin/soap2sam.pl soap2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/varfilter.py varfilter.py
    - ln -s ${HOME}/lib/samtools/bin/wgsim wgsim
    - ln -s ${HOME}/lib/samtools/bin/wgsim_eval.pl wgsim_eval.pl
    - ln -s ${HOME}/lib/samtools/bin/zoom2sam.pl zoom2sam.pl

    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq
    - docker run -p 80:80 --name biobambamcontainer multiscalegenomics/mgprocessfastq:biobambamimage
    - pwd

    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq
    - chmod +x shims/*
    - export PATH="$PWD/shims:$PATH"
    - docker ps -a

    - cd ${HOME}/build/Multiscale-Genomics/mg-process-fastq
    - chmod +x scripts/travis/harness.sh
    - ls tests/data/
    - git status

script :
    "./scripts/travis/harness.sh"

