language: "python"

python:
  - "2.7.12"
#  - "3.5.0"

sudo: false

addons:
  apt:
    packages:
    #system environment
    - make 
    - build-essential
    - libssl-dev 
    - zlib1g-dev
    - libbz2-dev 
    - libreadline-dev
    - libsqlite3-dev 
    - wget curl 
    - llvm libncurses5-dev
    - libncursesw5-dev
    - xz-utils tk-dev
    - unzip mcl 
    - libgtk2.0-dev 
    - r-base-core
    - libcurl4-gnutls-dev
    - unzip   

env:
  - COVERALLS=false
  
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:

    #pyenv-pyenv-virtualenv
    #- git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
    - echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
    - echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
    - source ~/.bash_profile

    - git clone https://github.com/pyenv/pyenv-virtualenv.git ${PYENV_ROOT}/plugins/pyenv-virtualenv

    - pyenv install 2.7.12
    - pyenv virtualenv 2.7.12 mg-process-fastq
    
    - cd ${HOME}
    - mkdir bin lib code

    
install:

    
     #SAMtools
    - cd ${HOME}/lib
    - git clone https://github.com/samtools/htslib.git
    - cd htslib
    - autoheader
    - autoconf
    - ./configure --prefix=${HOME}/lib/htslib
    - make
    - make install

    - cd ${HOME}/lib
    - git clone https://github.com/samtools/samtools.git
    - cd samtools
    - autoheader
    - autoconf -Wno-syntax
    - ./configure --prefix=${HOME}/lib/samtools
    - make
    - make install


     #BioBamBam2
    - cd ${HOME}/lib
    - git clone https://github.com/gt1/libmaus2.git
    - cd libmaus2
    - libtoolize
    - aclocal
    - autoheader
    - automake --force-missing --add-missing
    - autoconf
    - ./configure --prefix=${HOME}/lib/libmaus2
    - make
    - make install

    - cd ${HOME}/lib
    - git clone https://github.com/gt1/biobambam2.git
    - cd biobambam2
    - autoreconf -i -f
    - ./configure --with-libmaus2=${HOME}/lib/libmaus2 --prefix=${HOME}/lib/biobambam2
    - make install
    

     #bedTools
    - wget https://github.com/arq5x/bedtools2/releases/download/v2.26.0/bedtools-2.26.0.tar.gz
    - tar -zxvf bedtools-2.26.0.tar.gz
    - cd bedtools2
    - make


    # Setup Symlinks
    - cd ${HOME}/bin

    - ln -s ${HOME}/lib/bedtools2/bin/bedtools bedtools

    - ln -s ${HOME}/lib/bedToBigBed bedToBigBed
    - ln -s ${HOME}/lib/wigToBigWig wigToBigWig
    
    - ln -s ${HOME}/lib/htslib/bin/bgzip bgzip
    - ln -s ${HOME}/lib/htslib/bin/htsfile htsfile
    - ln -s ${HOME}/lib/htslib/bin/tabix tabix

    - ln -s ${HOME}/lib/samtools/bin/ace2sam ace2sam
    - ln -s ${HOME}/lib/samtools/bin/blast2sam.pl blast2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/bowtie2sam.pl bowtie2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/export2sam.pl export2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/interpolate_sam.pl interpolate_sam.pl
    - ln -s ${HOME}/lib/samtools/bin/maq2sam-long maq2sam-long
    - ln -s ${HOME}/lib/samtools/bin/maq2sam-short maq2sam-short
    - ln -s ${HOME}/lib/samtools/bin/md5fa md5fa
    - ln -s ${HOME}/lib/samtools/bin/md5sum-lite md5sum-lite
    - ln -s ${HOME}/lib/samtools/bin/novo2sam.pl novo2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/plot-bamstats plot-bamstats
    - ln -s ${HOME}/lib/samtools/bin/psl2sam.pl psl2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/sam2vcf.pl sam2vcf.pl
    - ln -s ${HOME}/lib/samtools/bin/samtools samtools
    - ln -s ${HOME}/lib/samtools/bin/samtools.pl samtools.pl
    - ln -s ${HOME}/lib/samtools/bin/seq_cache_populate.pl seq_cache_populate.pl
    - ln -s ${HOME}/lib/samtools/bin/soap2sam.pl soap2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/varfilter.py varfilter.py
    - ln -s ${HOME}/lib/samtools/bin/wgsim wgsim
    - ln -s ${HOME}/lib/samtools/bin/wgsim_eval.pl wgsim_eval.pl
    - ln -s ${HOME}/lib/samtools/bin/zoom2sam.pl zoom2sam.pl
    - ln -s ${HOME}/lib/biobambam2/bin/bam12auxmerge bam12auxmerge
    - ln -s ${HOME}/lib/biobambam2/bin/bam12split bam12split
    - ln -s ${HOME}/lib/biobambam2/bin/bam12strip bam12strip
    - ln -s ${HOME}/lib/biobambam2/bin/bamadapterclip bamadapterclip
    - ln -s ${HOME}/lib/biobambam2/bin/bamadapterfind bamadapterfind
    - ln -s ${HOME}/lib/biobambam2/bin/bamalignfrac bamalignfrac
    - ln -s ${HOME}/lib/biobambam2/bin/bamauxmerge bamauxmerge
    - ln -s ${HOME}/lib/biobambam2/bin/bamauxsort bamauxsort
    - ln -s ${HOME}/lib/biobambam2/bin/bamcat bamcat
    - ln -s ${HOME}/lib/biobambam2/bin/bamchecksort bamchecksort
    - ln -s ${HOME}/lib/biobambam2/bin/bamclipreinsert bamclipreinsert
    - ln -s ${HOME}/lib/biobambam2/bin/bamcollate bamcollate
    - ln -s ${HOME}/lib/biobambam2/bin/bamcollate2 bamcollate2
    - ln -s ${HOME}/lib/biobambam2/bin/bamdownsamplerandom bamdownsamplerandom
    - ln -s ${HOME}/lib/biobambam2/bin/bamexplode bamexplode
    - ln -s ${HOME}/lib/biobambam2/bin/bamfilteraux bamfilteraux
    - ln -s ${HOME}/lib/biobambam2/bin/bamfilterflags bamfilterflags
    - ln -s ${HOME}/lib/biobambam2/bin/bamfilterheader bamfilterheader
    - ln -s ${HOME}/lib/biobambam2/bin/bamfilterheader2 bamfilterheader2
    - ln -s ${HOME}/lib/biobambam2/bin/bamfilterlength bamfilterlength
    - ln -s ${HOME}/lib/biobambam2/bin/bamfiltermc bamfiltermc
    - ln -s ${HOME}/lib/biobambam2/bin/bamfilternames bamfilternames
    - ln -s ${HOME}/lib/biobambam2/bin/bamfilterrg bamfilterrg
    - ln -s ${HOME}/lib/biobambam2/bin/bamfixmateinformation bamfixmateinformation
    - ln -s ${HOME}/lib/biobambam2/bin/bamflagsplit bamflagsplit
    - ln -s ${HOME}/lib/biobambam2/bin/bamheap2 bamheap2
    - ln -s ${HOME}/lib/biobambam2/bin/bamindex bamindex
    - ln -s ${HOME}/lib/biobambam2/bin/bamintervalcomment bamintervalcomment
    - ln -s ${HOME}/lib/biobambam2/bin/bamintervalcommenthist bamintervalcommenthist
    - ln -s ${HOME}/lib/biobambam2/bin/bamlastfilter bamlastfilter
    - ln -s ${HOME}/lib/biobambam2/bin/bammapdist bammapdist
    - ln -s ${HOME}/lib/biobambam2/bin/bammarkduplicates bammarkduplicates
    - ln -s ${HOME}/lib/biobambam2/bin/bammarkduplicates2 bammarkduplicates2
    - ln -s ${HOME}/lib/biobambam2/bin/bammarkduplicatesopt bammarkduplicatesopt
    - ln -s ${HOME}/lib/biobambam2/bin/bammaskflags bammaskflags
    - ln -s ${HOME}/lib/biobambam2/bin/bammdnm bammdnm
    - ln -s ${HOME}/lib/biobambam2/bin/bammerge bammerge
    - ln -s ${HOME}/lib/biobambam2/bin/bamnumericalindex bamnumericalindex
    - ln -s ${HOME}/lib/biobambam2/bin/bamrank bamrank
    - ln -s ${HOME}/lib/biobambam2/bin/bamranksort bamranksort
    - ln -s ${HOME}/lib/biobambam2/bin/bamrecalculatecigar bamrecalculatecigar
    - ln -s ${HOME}/lib/biobambam2/bin/bamrecompress bamrecompress
    - ln -s ${HOME}/lib/biobambam2/bin/bamreset bamreset
    - ln -s ${HOME}/lib/biobambam2/bin/bamscrapcount bamscrapcount
    - ln -s ${HOME}/lib/biobambam2/bin/bamseqchksum bamseqchksum
    - ln -s ${HOME}/lib/biobambam2/bin/bamsormadup bamsormadup
    - ln -s ${HOME}/lib/biobambam2/bin/bamsort bamsort
    - ln -s ${HOME}/lib/biobambam2/bin/bamsplit bamsplit
    - ln -s ${HOME}/lib/biobambam2/bin/bamsplitdiv bamsplitdiv
    - ln -s ${HOME}/lib/biobambam2/bin/bamstreamingmarkduplicates bamstreamingmarkduplicates
    - ln -s ${HOME}/lib/biobambam2/bin/bamtagconversion bamtagconversion
    - ln -s ${HOME}/lib/biobambam2/bin/bamtofastq bamtofastq
    - ln -s ${HOME}/lib/biobambam2/bin/bamvalidate bamvalidate
    - ln -s ${HOME}/lib/biobambam2/bin/bamzztoname bamzztoname
    - ln -s ${HOME}/lib/biobambam2/bin/fastaexplode fastaexplode
    - ln -s ${HOME}/lib/biobambam2/bin/fastqtobam fastqtobam
    - ln -s ${HOME}/lib/biobambam2/bin/fastqtobampar fastqtobampar
    - ln -s ${HOME}/lib/biobambam2/bin/filtersam filtersam
    - ln -s ${HOME}/lib/biobambam2/bin/kmerprob kmerprob
    - ln -s ${HOME}/lib/biobambam2/bin/lasToBAM lasToBAM
    - ln -s ${HOME}/lib/biobambam2/bin/normalisefasta normalisefasta
    
    ##Prepare the Python Environment
     #Install APIs and Pipelines
    - cd ${HOME}/code
    - pyenv activate mg-process-fastq
    - pip install git+https://github.com/Multiscale-Genomics/mg-dm-api.git

    - git clone https://github.com/Multiscale-Genomics/mg-process-fastq.git
    - cd mg-process-fastq
    - pip install --editable .

    

#script : "./tests/test_biobambam.py"

