language: "python"

python:
  - "2.7.12"
#  - "3.5.0"

#sudo: false

addons:
  apt:
    packages:
    #system environment
    - make 
    - build-essential
    - libssl-dev 
    - zlib1g-dev
    - libbz2-dev 
    - libreadline-dev
    - libsqlite3-dev 
    - wget curl 
    - llvm libncurses5-dev
    - libncursesw5-dev
    - xz-utils tk-dev
    - unzip mcl 
    - libgtk2.0-dev 
    - r-base-core
    - libcurl4-gnutls-dev
    - unzip   

env:
  - COVERALLS=false
  
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:

    #pyenv-pyenv-virtualenv
    #- which python
    #- git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    #- echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
    #- echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
    #- echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
    #- source ~/.bash_profile

    #- git clone https://github.com/pyenv/pyenv-virtualenv.git ${PYENV_ROOT}/plugins/pyenv-virtualenv
    
    - cd ${HOME}
    - mkdir bin lib code

    
install:    
    
    #UCSC Tools
    - cd ${HOME}/lib
    - wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed
    - wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig
    
        
    #Bowtie2 Aligner
    - cd ${HOME}/lib
    - wget --max-redirect 1 https://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.3.2/bowtie2-2.3.2-linux-x86_64.zip
    - unzip bowtie2-2.3.2-linux-x86_64.zip


    #BWA Sequence Aligner
    - cd ${HOME}/lib
    - git clone https://github.com/lh3/bwa.git
    - cd bwa
    - make

    
    #iNPS Peak Caller
    - cd ${HOME}/lib
    - mkdir iNPS
    - cd iNPS
    - wget http://www.picb.ac.cn/hanlab/files/iNPS_V1.2.2.zip
    - unzip iNPS_V1.2.2.zip


    #Kallisto
    - cd ${HOME}/lib
    - wget https://github.com/pachterlab/kallisto/releases/download/v0.43.1/kallisto_linux-v0.43.1.tar.gz
    - tar -xzf kallisto_linux-v0.43.1.tar.gz
       
    
     #SAMtools
    - cd ${HOME}/lib
    - git clone https://github.com/samtools/htslib.git
    - cd htslib
    - autoheader
    - autoconf
    - ./configure --prefix=${HOME}/lib/htslib
    - make
    - make install

    - cd ${HOME}/lib
    - sudo apt-get install samtools

   
     #bedTools
    - wget https://github.com/arq5x/bedtools2/releases/download/v2.26.0/bedtools-2.26.0.tar.gz
    - tar -zxvf bedtools-2.26.0.tar.gz
    - cd bedtools2
    - make
    


    # Setup Symlinks
    - cd ${HOME}/bin

    - ln -s ${HOME}/lib/bedtools2/bin/bedtools bedtools

    - ln -s ${HOME}/lib/bedToBigBed bedToBigBed
    - ln -s ${HOME}/lib/wigToBigWig wigToBigWig
    
    - ln -s ${HOME}/lib/htslib/bin/bgzip bgzip
    - ln -s ${HOME}/lib/htslib/bin/htsfile htsfile
    - ln -s ${HOME}/lib/htslib/bin/tabix tabix

    - ln -s ${HOME}/lib/samtools/bin/ace2sam ace2sam
    - ln -s ${HOME}/lib/samtools/bin/blast2sam.pl blast2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/bowtie2sam.pl bowtie2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/export2sam.pl export2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/interpolate_sam.pl interpolate_sam.pl
    - ln -s ${HOME}/lib/samtools/bin/maq2sam-long maq2sam-long
    - ln -s ${HOME}/lib/samtools/bin/maq2sam-short maq2sam-short
    - ln -s ${HOME}/lib/samtools/bin/md5fa md5fa
    - ln -s ${HOME}/lib/samtools/bin/md5sum-lite md5sum-lite
    - ln -s ${HOME}/lib/samtools/bin/novo2sam.pl novo2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/plot-bamstats plot-bamstats
    - ln -s ${HOME}/lib/samtools/bin/psl2sam.pl psl2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/sam2vcf.pl sam2vcf.pl
    - ln -s ${HOME}/lib/samtools/bin/samtools samtools
    - ln -s ${HOME}/lib/samtools/bin/samtools.pl samtools.pl
    - ln -s ${HOME}/lib/samtools/bin/seq_cache_populate.pl seq_cache_populate.pl
    - ln -s ${HOME}/lib/samtools/bin/soap2sam.pl soap2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/varfilter.py varfilter.py
    - ln -s ${HOME}/lib/samtools/bin/wgsim wgsim
    - ln -s ${HOME}/lib/samtools/bin/wgsim_eval.pl wgsim_eval.pl
    - ln -s ${HOME}/lib/samtools/bin/zoom2sam.pl zoom2sam.pl
    
    ##Prepare the Python Environment
     #Install APIs and Pipelines
    - cd ${HOME}/code
    #- pyenv #activate mg-process-fastq
    - pip install git+https://github.com/Multiscale-Genomics/mg-dm-api.git

    - git clone https://github.com/Multiscale-Genomics/mg-process-fastq.git
    - cd mg-process-fastq
    - pip install --editable .

    

#script : "./tests/test_biobambam.py"

